{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fastapi-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useUserAssignedIdentity: "true"
    clientID: "{{ .Values.keyVault.managedIdentityClientId }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-USER
          objectType: secret
{{- end }}
