apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: { { .Values.namespace } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: fastapi
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
