apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: devops-keyvault
  namespace: default # Adicionar namespace é boa prática
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useUserAssignedIdentity: "true"
    userAssignedIdentityID: "/subscriptions/<SUBSCRIPTION_ID>/resourcegroups/<RG_NAME>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY_NAME>"
    clientID: "<MANAGED_IDENTITY_CLIENT_ID>"
    keyvaultName: "kv-devops-dev"
    cloudName: "AzurePublicCloud"
    tenantId: "$(tenantId)"

    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: DB-USER
          objectType: secret
          objectVersion: ""

    # Mapeia secrets para arquivos no filesystem do pod
    secretObjects:
      - secretName: devops-db-secrets
        type: Opaque
        data:
          - objectName: DB-HOST
            key: db-host
          - objectName: DB-USER
            key: db-user
