apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: devops-app
  labels:
    app: fastapi
    tier: backend
spec:
  type: ClusterIP # Mantemos ClusterIP porque usaremos um Ingress como porta de entrada
  selector:
    app: fastapi
  ports:
    - name: http-api
      protocol: TCP
      port: 80 # Porta que o Service expõe dentro do cluster
      targetPort: 8000 # Porta que a aplicação FastAPI está ouvindo no container
